apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    app: node-app
  strategy:
    rollingParams:
      intervalSeconds: 2
      maxSurge: 1
      maxUnavailable: 0
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: node-app:latest
        imagePullPolicy: Always
        name: node-app
        ports:
        - containerPort: 3000
          protocol: TCP
